#!/usr/bin/env bash
# Connects to my alx server

sudo ssh -i ~/.ssh/id_rsa ubuntu@100.26.236.251

#!/usr/bin/env bash
# Connects to my alx server

# Server-01
#sudo ssh -i ~/.ssh/id_rsa ubuntu@100.26.236.251

# Server-02
#sudo ssh -i ~/.ssh/id_rsa ubuntu@54.236.47.141

# Load balancer
sudo ssh -i ~/.ssh/id_rsa ubuntu@54.197.21.207